pokemon:
  - windows
  - angular
  - blogspot
  - bootstrap
  - codeigniter
  - coffeescript
  - css
  - elementary
  - git
  - github
  - gitlab
  - html
  - hugo
  - javascript
  - sublime
  - android
  - jekyll
  - jquery
  - kali
  - laravel
  - linux
  - materialize
  - php
  - python
  - spectre
  - vue
  - eclipse

hiburan:
  -
    nama: Blogwalking
    link: /blogwalking2
    ikon: blogger

pendidikan:
  -
    nama: Font
    link: /font
    ikon: fonts
  -
    nama: Kaligrafi
    link: /kaligrafi
    ikon: calligrakrita