skill:
- Vue
- Bootstrap
- PHP
- Javascript
- Jekyll
- MySQL
- YAML
- HTML
- CSS
- Fetch API
proyek_pribadi:
- gambar: https://i.ibb.co/XC42D5Z/Screenshot-2020-07-31-17-13-13-00.png
  link: https://mzaini30.js.org/catatan/#/