pokemon:
  - windows
  - angular
  - blogspot
  - bootstrap
  - codeigniter
  - coffeescript
  - css
  - elementary
  - git
  - github
  - gitlab
  - html
  - hugo
  - javascript
  - sublime
  - android
  - jekyll
  - jquery
  - kali
  - laravel
  - linux
  - materialize
  - php
  - python
  - spectre
  - vue
  - eclipse