permalink: /:year/:month/:day/:title.html
link:
  -
    title: Play Store
    link: https://play.google.com/store/apps/dev?id=6751907367958089476
  -
    title: Email
    link: mailto:muhzaini30@gmail.com
  -
    title: Whatsapp
    link: https://wa.me/6281545143654
  -
    title: Github
    link: https://github.com/mzaini30
  -
    title: Blog
    link: /blog
