title: Zen
description: Android developer.

paginate: 10

plugins:
  - jekyll-paginate

menu:
  -
    title: Github
    link: http://github.com/mzaini30
  -
    title: Email
    link: mailto:muhzaini30@gmail.com
  -
    title: Play Store
    link: http://gg.gg/zenapk

spesial: 'Special for International Women\'s Day'
spesial_list:
  - /2019/02/11/kekuatan-dalam-sunyi.html