skill:
- Vue
- Bootstrap
- PHP
- Javascript
- Jekyll
- MySQL
- YAML
- HTML
- CSS
- Fetch API
proyek_pribadi:
- link: https://mzaini30.js.org/catatan/#/
  gambar: https://i.ibb.co/XC42D5Z/Screenshot-2020-07-31-17-13-13-00.png
- link: https://mzaini30.js.org/efektif/#/
  gambar: https://i.ibb.co/L1yqK9Y/Screenshot-2020-07-31-17-23-47-63.png