skill:
  -
    judul: 10 Fast Fingers
    link: https://10fastfingers.com/user/1452563/
    icon: keyboard-o
  -
    judul: Project Euler
    link: https://projecteuler.net/profile/mzaini30.png
    icon: free-code-camp

sharing:
  -
    judul: Medium
    link: https://medium.com/@mzaini30
    icon: medium
  -
    judul: Github
    link: http://github.com/mzaini30
    icon: github
  -
    judul: Play Store
    link: https://play.google.com/store/apps/dev?id=6751907367958089476
    icon: android
  -
    judul: Cloud (private)
    link: http://gitlab.com/mzaini30/cloud
    icon: cloud
  -
    judul: Aplikasi Web
    link: https://github.com/mzaini30/web-apps
    icon: globe

kontak:
  -
    judul: Whatsapp
    link: https://api.whatsapp.com/send?phone=6281545143654
    icon: whatsapp
  -
    judul: Email
    link: mailto:muhzaini30@gmail.com
    icon: envelope-o