title: Zen
description: Android developer.

timezone: Asia/Makassar

paginate: 10

plugins:
  - jekyll-paginate

spesial: "Special for International Women's Day"
spesial_list:
  - /2019/02/11/kekuatan-dalam-sunyi.html