# Site settings
title: Zen
description: Kumpulan eksperimen website oleh Zen
# baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://mzaini30.js.org" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Zen
user_description: Developer website
email: muhzaini30@gmail.com
twitter_username: mzaini30
github_username:  mzaini30
# gplus_username:  lorem_ipsum
disqus_username: laptopzen

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /postingan-:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
# links:
#   - title: Home
#     url: /
#   - title: Series
#     url: /series
#   - title: Tags
#     url: /tags
#   - title: About Me
#     url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
