title: "Zen | blog psikologi"

permalink: /:year/:month/:day/:title/

paginate: 10

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  
name: Zen
description: Blogger Psikologi
url: http://muhammadzaini.com

author:
  twitter: mzaini30
  
timezone: Asia/Makassar

komunitas:
  -
    gambar: /gambar/komunitas/blog.jpg
    link: https://chat.whatsapp.com/KBzZzO25l1mLoEatsjHWAw
    
menu:
  -
    nama: Portofolio
    link: http://muhammadzaini.com