klien:
  -
    nama: Antrian Rumah Tahanan Samarinda
    situs: http://antrianrutansamarinda.com/index.php/login
    gambar: rutan.png

aplikasi:
  -
    nama: Materialize Color
    situs: https://www.muhammadzaini.com/color30/
    gambar: materialize.png