klien:
  -
    nama: Antrian Rumah Tahanan Samarinda
    situs: http://antrianrutansamarinda.com/index.php/login
    gambar: rutan.png
  -
    nama: Sanggar Caraka
    situs: https://www.sanggarcaraka.com/
    gambar: sanggar.png

aplikasi:
  -
    nama: Materialize Color
    situs: https://www.muhammadzaini.com/color30/
    gambar: materialize.png
  -
    nama: Undian
    situs: https://www.muhammadzaini.com/undian/
    gambar: undian.png