sharing:
  -
    judul: Play Store
    link: https://play.google.com/store/apps/dev?id=6751907367958089476
    icon: android
  -
    judul: Aplikasi Web
    link: /web-apps
    icon: globe
  -
    judul: Instagram
    link: https://www.instagram.com/mzaini30/
    icon: instagram
  -
    judul: Blog
    link: http://blog.muhammadzaini.com
    icon: rss

kontak:
  -
    judul: Whatsapp
    link: https://api.whatsapp.com/send?phone=6281545143654
    icon: whatsapp
  -
    judul: Email
    link: mailto:muhzaini30@gmail.com
    icon: envelope-o

lainnya:
  -
    judul: Cloud (private)
    link: https://gitlab.com/mzaini30/cloud/blob/master/README.md
    icon: cloud