pokemon:
  - windows
  - angular
  - blogspot
  - bootstrap
  - codeigniter
  - coffeescript
  - css
  - elementary
  - git
  - github
  - gitlab
  - html
  - hugo
  - javascript
  - sublime
  - android
  - jekyll
  - jquery
  - kali
  - laravel
  - linux
  - materialize
  - php
  - python
  - spectre
  - vue
  - eclipse

hiburan:
  -
    nama: Blogwalking
    link: /blogwalking2
    ikon: blogger

pendidikan:
  -
    nama: Font
    link: /font
    ikon: fonts
  -
    nama: Kaligrafi
    link: /kaligrafi
    ikon: calligrakrita
  -
    nama: Murajaah Simpel
    link: /murajaah-simple
    ikon: gnome-books
  -
    nama: Murajaah
    link: /murajaah
    ikon: google-play-books
  -
    nama: Sekolah Impian
    link: /sekolah-impian
    ikon: AdobeWidgetBrowser
  -
    nama: Tutorial Jade
    link: /tutorialjade
    ikon: altyo

works:
  -
    nama: Medium
    link: http://medium.com/@mzaini30
  -
    nama: Google Maps
    link: https://goo.gl/maps/pKsi6DWxrDz
  -
    nama: Ask FM
    link: https://ask.fm/mzaini30
  -
    nama: Gitlab
    link: https://gitlab.com/mzaini30
  -
    nama: Github
    link: https://github.com/mzaini30
  -
    nama: Twitter
    link: https://twitter.com/mzaini30
  -
    nama: Facebook
    link: https://facebook.com/mzaini30
  -
    nama: Project Euler
    link: https://projecteuler.net/profile/mzaini30.png
  -
    nama: Codepolitan
    link: https://www.codepolitan.com/coder/mzaini30