permalink: /:year/:month/:day/:title.html

title: Zen
description: Waiting me my love.
image: https://vignette.wikia.nocookie.net/kyoukainokanata/images/7/7c/Kyoukai_no_Kanata_1.jpg/revision/latest/scale-to-width-down/670?cb=20180212024327

link:
  -
    title: Play Store
    link: https://play.google.com/store/apps/dev?id=6751907367958089476
  -
    title: Email
    link: mailto:muhzaini30@gmail.com
  -
    title: Whatsapp
    link: https://wa.me/6281545143654
  -
    title: Github
    link: https://github.com/mzaini30
  -
    title: Instagram
    link: https://www.instagram.com/mzaini30/
  -
    title: Facebook
    link: https://web.facebook.com/mzaini30?_rdc=1&_rdr
  -
    title: Telegram
    link: https://t.me/mzaini30a
  -
    title: Messenger
    link: https://www.messenger.com/t/100000415959373/

paginate: 10

plugins:
  - jekyll-paginate