url: http://muhammadzaini.com
description: 'Senyumlah :)'
gambar: https://img00.deviantart.net/920b/i/2013/306/5/7/daisuki_by_dasketcherz-d6sp979.png
lokasi: '/media/data/web/mzaini30.github.io (git)'
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-paginate
  - jekyll-archives
paginate: 5
permalink: /:year/:month/:day/:title.html

jekyll-archives:
  enabled: all
  layouts:
    year: archive/year
    month: archive/month
    day: archive/day
    tag: archive/tag
    category: archive/category
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tags/:name/'
    category: '/category/:name/'