title: Zen
description: Android developer.

paginate: 10

plugins:
  - jekyll-paginate

menu:
  -
    title: Email
    link: mailto:muhzaini30@gmail.com
  -
    title: Play Store
    link: http://gg.gg/zenapk